spring.config.activate.on-profile: docker

## the following username & password are basic auth credentials that are used to protect access to eureka server..
## any client that wants to register it self in eureka or discover services shall provide this username & password
app:
  eureka-username: u
  eureka-password: p
  eureka-server: eureka
  auth-server: auth-server    
  
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
   
###############################
## Actuators related configs ##
###############################    
# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
