spring.config.activate.on-profile: docker

insta.post-service.virtual-url: http://post-ms    ## url to discover the actual url of the service from eureka
insta.user-info-service.virtual-url: http://user-ms
## the following username & password are basic auth credentials that are used to protect access to eureka server..
## any client that wants to register it self in eureka or discover services shall provide this username & password
app:
  eureka-username: u
  eureka-password: '{cipher}8059cb5b292ce59006e227215a06b2a35c65825af3f847a9540d7e022fecb447'
  eureka-server: eureka
  auth-server: auth-server    
  
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
#####################################
## Database related configurations ##
#####################################
    
spring:
  jpa:
    properties:
      hibernate.format_sql: true    
   
###############################
## Actuators related configs ##
###############################    
# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

#####################################
## message brokers related configs ##
#####################################
spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: '{cipher}17fcf0ae5b8c5cf87de6875b699be4a1746dd493a99d926c7a26a68c422117ef'

#################################
## distributed tracing configs ##
#################################    

spring.zipkin.sender.type: rabbit
spring.sleuth.sampler.probability: 1.0




