server:
  port: 8080

#####################################
## Database related configurations ##
#####################################

##spring.jpa.hibernate.ddl-auto: create # TODO: Strongly recommend to set this property to "none" in a production environment!

spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  

spring.datasource:
  url: jdbc:mysql://mysql/post-db 
  username: root
  password: rootpwd

# TODO: logging SQL queries should be disabled on production env as it heavily affects the performance
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.javaworld.instagram.postservice.commons.utils.LoggingUtil: DEBUG  ## this is not related to database config..it is just added here to benefit from YAML properties nesting


spring:
  liquibase:
    ##changeLog: "classpath:dblogs\changelog\changelog-master.xml"
    enabled: true
    

    

########################################
## Auth server related configurations ##
########################################

##TODO: shall we move this property to the common configurations file ?
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999


#######################
## messaging configs ##
#######################

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: posts   ## topic name
    group: postsGroup    ## a message pushed to posts topic will be consumed by one instance of post-ms even if
                         ## we have mutiple instances of it

    
spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true


    
    
    