version: '2.1'

services:

  insta-ms-post:
    build: post-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}      
    depends_on:
      mysql:
        condition: service_healthy

  insta-ms-user-info:
    build: user-info-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}      
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
      
  eureka:
    build: eureka-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker  
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD} 
      
  auth-server:
    build: authorization-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker  
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}      
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:9999/actuator/health"]  ## TODO: leh localhost..msh el mafrood bnklm el service be el url bta3ha 3la el cluster lw el call mn gwa el cluster
      interval: 5s
      timeout: 2s
      retries: 60

  gateway:
    build: gateway
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker  
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    ports:
      - "8443:8443"    
    depends_on:
      auth-server:
        condition: service_healthy
      
  config-server:
    build: config-server
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - ./config-repo:/config-repo
    