version: '2.1'

services:

  insta-ms-post:
    build: post-service
    mem_limit: 512m
    ports:
      - "7001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  insta-ms-user-info:
    build: user-info-service
    mem_limit: 512m
    ports:
      - "7002:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
      
  eureka:
    build: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"  
    