spring.config.activate.on-profile: docker

server:
  port: 8080
  servlet.context-path: /insta-post-service




# TODO: Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: create

spring.datasource:
  url: jdbc:mysql://mysql/post-db
  username: root
  password: rootpwd

  
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  

# TODO: logging SQL queries should be disabled on production env as it heavily affects the performance
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
    
 
spring.application.name: post  ##used by EUREKA to identify each micro service
app.eureka-server: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5 
    
  