server:
  port: 7001
  servlet.context-path: /services

spring:
  main:
    allow-bean-definition-overriding: true

###################################
## Eureka related configurations ##
###################################

spring.application.name: post-ms  ##used by EUREKA to identify each micro service

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: auth-server ## this is not related to eureka..it is just added here to benefit from YAML properties nesting
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5 

#####################################
## Database related configurations ##
#####################################

spring.jpa.hibernate.ddl-auto: create # TODO: Strongly recommend to set this property to "none" in a production environment!
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  

spring.datasource:
  url: jdbc:mysql://localhost:3306/user-info-db 
  username: root
  password: rootpwd

# TODO: logging SQL queries should be disabled on production env as it heavily affects the performance
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


########################################
## Auth server related configurations ##
########################################


spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysql/post-db
app:
  eureka-server: eureka
  auth-server: auth-server
  
    
  