spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/post-db
  username: root
  password: rootpwd

  
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  
  