server:
  port: 7001
  servlet.context-path: /services

spring.jpa.hibernate.ddl-auto: create # TODO: Strongly recommend to set this property to "none" in a production environment!
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  
spring.datasource:
  url: jdbc:mysql://localhost:3306/post-db
  username: root
  password: rootpwd


# TODO: logging SQL queries should be disabled on production env as it heavily affects the performance
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


---
spring.config.activate.on-profile: docker

server.port: 8080
spring.datasource.url: jdbc:mysql://mysql/post-db


spring.application.name: post-ms  ##used by EUREKA to identify each micro service
app.eureka-server: eureka

##TODO: check if we can move this to default profile properties and make it work when running locally
## i think that was done in the book example
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5 
    
  