openapi: 3.0.3
info:
  title: "instagram-post-service"
  description: ""
  termsOfService: ""
  version: 1.0.0
externalDocs:
  description: ""
  url: ""
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Post
    description: Operations about posts
    externalDocs:
      description: ""
      url: ""
  - name: Comment
    description: Operations about comments
    externalDocs:
      description: ""
      url: ""
    
paths:
  /posts:                  
    post:
      tags:
        - Post
      summary: Create a new Post
      description: ''
      operationId: createPost
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'     

  /posts/findByUserId:
    get:
      tags:
        - Post
      summary: Finds posts by userId
      description: ''
      operationId: findPostsByUserId
      parameters:
        - name: userId
          in: query
          description: ''
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'          
        '400':
          description: Invalid userId
          
  /posts/count:
    get:
      tags:
        - Post
      summary: Finds posts count for a certain user
      description: ''
      operationId: findPostsCount
      parameters:
        - name: userId
          in: query
          description: ''
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostsCountResponse'          
        '400':
          description: Invalid userId          

  /posts/deleteByUuid:
    delete:
      tags:
        - Post
      summary: delete posts by uuid
      description: ''
      operationId: deletePostsByUuuid
      parameters:
        - in: query
          name: postUuid
          description: ''
          explode: false
          schema:
            type: array
            items:
              type: string          

      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid userId          

components:
  schemas:
    Post:
      type: object
      properties:
        title:
          type: string
        userId:
          type: integer    
          format: int32
        postUuid:
          type: string    
          format: uuid          
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'        
        serviceAddress:
          type: string  
          
    Tag:
      type: object
      properties:
        name:
          type: string
  
          
    PostsCountResponse:
      type: object
      properties:
        postsCount:
          type: integer    
          format: int32
        serviceAddress:
          type: string
          