spring.config.import: "configserver:"

spring:
  application.name: gateway ##used by EUREKA to identify each micro service
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
    username: ${CONFIG_SERVER_USR} ## set from docker compose environment variables for this ms
    password: ${CONFIG_SERVER_PWD} ## set from docker compose environment variables for this ms
        
---
spring.config.activate.on-profile: docker

app:
  eureka-server: eureka
  auth-server: auth-server

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999  
spring.cloud.config.uri: http://config-server:8888 


