
server.port: 8080

#################################
## using HTTPS instead of HTTP ##
#################################

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12   ## this is the path of the certificate..it is stored in the app jar
  key-store-password: password             ## this password is provided during certificate creation
  key-alias: localhost


###################################
## Eureka related configurations ##
###################################

spring.application.name: gateway  ##used by EUREKA to identify each micro service

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost  ##used when running the service locally outside the cluster
  auth-server: auth-server ## this is not related to eureka..it is just added here to benefit from YAML properties nesting
  

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


#################################################
## Authorization server related configurations ##
#################################################
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

######################################
## Actuators related configurations ##
######################################

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"


####################################
## Routes related configurations  ##
####################################

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    
spring.cloud.gateway.routes:

- id: post-micro-service
  uri: lb://post-ms   ## name used by service to be registered in eureka
  predicates:
  - Path=/services/posts/**

- id: user-info-micro-service
  uri: lb://user-ms   ## name used by service to be registered in eureka
  predicates:
  - Path=/services/users/**

  
  ## routing rules for eureka
  ## the url for eureka api without the gateway is: //${app.eureka-server}:8761/eureka 
- id: eureka-api
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/api/{segment}
  filters:
  - SetPath=/eureka/{segment}

  ## the url for eureka web without the gateway is: //${app.eureka-server}:8761
- id: eureka-web-start
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/web
  filters:
  - SetPath=/
  
  ## this is needed for loading .css & .js & .png files when accessing the eureka web page 
- id: eureka-web-other
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/**
  
    
---
spring.config.activate.on-profile: docker
app:
  eureka-server: eureka
  auth-server: auth-server
