server.port: 7001
spring:
  application.name: user-ms
  cloud.config.enabled: false  # disable spring config server
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

eureka.client.enabled: false  # disable eureka

# spring auth server config
spring.security:
    oauth2:
      resourceserver.jwt.issuer-uri: http://${auth-server.uri}:9999
      ## the following configuration is needed for the webclient filter that will call the auth-server
      ## to get an access token when the service needs to call another service
      client:
        registration:
          mywebclient:
            client-id: user-ms
            client-secret: my-secret-01 # TODO: update in liquibase  with corresponding bcrypt hashed value
            authorization-grant-type: client_credentials
        provider:
          mywebclient:
            issuer-uri: http://${auth-server.uri}:9999

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://mysql/user-info-db
    username: root
    password: rootpwd

post-ms.uri: "http://localhost:7002" # todo: to be changed
auth-server.uri: localhost  # todo: to be changed

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost/user-info-db
    username: root
    password: rootpwd

auth-server.uri: localhost
post-ms.uri: "http://localhost:7002"