server:
  port: 7002
  servlet.context-path: /services

insta.post-service.url: http://localhost:7001 
insta.post-service.virtual-url: http://post-ms

spring.jpa.hibernate.ddl-auto: create # TODO: Strongly recommend to set this property to "none" in a production environment!

spring.datasource:
  url: jdbc:mysql://localhost:3306/user-info-db 
  username: root
  password: rootpwd


spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect  

# TODO: logging SQL queries should be disabled on production env as it heavily affects the performance
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


---

spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysql/user-info-db 

insta.post-service.url: http://insta-ms-post
insta.post-service.virtual-url: http://post-ms
    

## configuring user service to call eureka
#########################################################################    
spring.application.name: user-ms  ##used by EUREKA to identify each micro service
app.eureka-server: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5 
    
  