swagger: "2.0"
info:
  description: ""
  version: "1.0"
  title: "insta-ms-user-info-api"
  termsOfService: ""
  contact:
    email: "abdelrahmanattya94@gmail.com"
host: "localhost"
basePath: "/"
schemes:
  - http

tags:
  - name: User
    description: Operations about users
  - name: Reports
    description: Operations about user account information report

    
paths:
  /users/:                  
    post:
      tags:
        - User
      summary: Create a new user
      description: ''
      operationId: createUser
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "CreateUserRequest"
          description: "Invoice buckets request"
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/User'     
            
    patch:
      tags:
        - User
      summary: Create a new user
      description: ''
      operationId: partialUpdateUser
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "invoiceBuckets"
          description: "Invoice buckets request"
          required: true
          schema:
            $ref: '#/definitions/PartialUpdateUserRequest'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/User'                

    get:
      tags:
        - User
      summary: Find user
      description: ''
      operationId: findUser
      produces:
        - "application/json"
      parameters:
        - in: query
          name: userUuid
          description: ''
          required: true
          type: string
          format: uuid
        - in: query
          name: delay
          description: 'The amount of delay in milliseconds to simulate network latency'
          required: false
          type: integer
          default: 0
        - in: query
          name: faultPercent
          description: 'The percentage of requests that should return a fault response'
          required: false
          type: integer
          default: 0
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid userId
          
    delete:
      tags:
        - User
      summary: Delete user
      description: ''
      operationId: deleteUser
      produces:
        - "application/json"
      parameters:
        - in: query
          name: userUuid
          description: ''
          required: true
          type: string
          format: uuid
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DeletedUsersResponse'
        '400':
          description: Invalid userId

  /users/suggested:              
    get:
      tags:
        - User
      summary: get suggested users
      description: ''
      operationId: getSuggestedUsers
      produces:
        - "application/json"
      parameters:
        - in: query
          name: size
          description: ''
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '400':
          description: ''


  /users/follow:              
    post:
      tags:
        - User
      summary: send a follow request to another user
      description: ''
      operationId: followUser
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "FollowUserRequest"
          description: ""
          required: true
          schema:
            $ref: '#/definitions/FollowUserRequest'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/GenericResponse'     

  /reports/downloadaccountinformationreport:                  
    get:
      tags:
        - Reports
      summary: download user account information report
      description: ''
      operationId: downloadAccountInformationReport
      produces:
        - application/pdf
      parameters:
        - in: query
          name: userName
          description: ''
          required: true
          type: string
      responses:
        200:
          description: Successful operation
          schema:
            type: string
            format: binary
          
        
definitions:
  User:
    type: object
    properties:
      name:
        type: string
      username:
        type: string    
      email:
        type: string 
      password:
        type: string 
      postsCount:
        type: integer
      followersCount:
        type: integer
      followingCount:
        type: integer
      userUuid:
        type: string    
        format: uuid   
      profileImageName:
        type: string           
      serviceAddress:
        type: string 
        
  CreateUserRequest:
    type: object
    required:
      - mobileNumberOrEmail
      - username
      - password
    properties:
      mobileNumberOrEmail:
        type: string
      fullName:
        type: string
      username:
        type: string    
      password:
        type: string 
        
  FollowUserRequest:        
    type: object
    required:
      - followerId
      - followedId
    properties:
      followerId:
        type: string
        format: uuid  
      followedId:
        type: string
        format: uuid  
    
    
  PartialUpdateUserRequest:
    type: object
    required:
      - userUuid    
    properties:
      userUuid:   
        type: string    
        format: uuid   
      profileImageName:
        type: string        
      mobileNumber:
        type: string
      email:
        type: string
      username:
        type: string    
      password:
        type: string 
 
  DeletedUsersResponse:
    type: object
    properties:
      deletedUsersCount:
        type: integer    
        format: int32
        example: 4
      message:
        type: string
        example: users deleted successfully
      serviceAddress:
        type: string

  GenericResponse:
    type: object
    properties:
      message:
        type: string
        example: message
      serviceAddress:
        type: string   
