openapi: 3.0.3
info:
  title: "instagram-userinfo-service"
  description: ""
  termsOfService: ""
  version: 1.0.0
externalDocs:
  description: ""
  url: ""
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: User
    description: Operations about users
    externalDocs:
      description: ""
      url: ""

    
paths:
  /users/:                  
    post:
      tags:
        - User
      summary: Create a new user
      description: ''
      operationId: createUser
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'     

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        username:
          type: string    
        email:
          type: string 
        password:
          type: string 
        serviceAddress:
          type: string      
          
          
