openapi: 3.0.3
info:
  title: "instagram-userinfo-service"
  description: ""
  termsOfService: ""
  version: 1.0.0
externalDocs:
  description: ""
  url: ""
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: User
    description: Operations about users
    externalDocs:
      description: ""
      url: ""

    
paths:
  /users/:                  
    post:
      tags:
        - User
      summary: Create a new user
      description: ''
      operationId: createUser
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'     

    get:
      tags:
        - User
      summary: Find user
      description: ''
      operationId: findUser
      parameters:
        - name: userUuid
          in: query
          description: ''
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '400':
          description: Invalid userId


components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        username:
          type: string    
        email:
          type: string 
        password:
          type: string 
        postsCount:
          type: integer
        followersCount:
          type: integer
        followingCount:
          type: integer
        userUuid:
          type: string    
          format: uuid          
        serviceAddress:
          type: string 
          
    CreateUserRequest:
      type: object
      properties:
        username:
          type: string    
        email:
          type: string 
        password:
          type: string 
        serviceAddress:
          type: string 

       