server:
  port: 8761

## the following username & password are basic auth credentials that are used to protect access to eureka server..
## any client that wants to register it self in eureka or discover services shall provide this username & password
app:
  eureka-username: u
  eureka-password: p

eureka:
  instance:
    hostname: localhost   ##TODO: is this correct
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000
